apiVersion: v1
kind: Pod
metadata:
  name: nginx-simple-logging
  labels:
    component: nginx
    logging: simple
spec:
  containers:
    - name: web
      image: demo-nginx:simple
      ports:
        - name: web
          containerPort: 80
