apiVersion: v1
kind: Pod
metadata:
  name: nginx-json-logging
  labels:
    component: nginx
    logging: json
spec:
  containers:
    - name: web
      image: demo-nginx:json
      ports:
        - name: web
          containerPort: 80
